name: Story
description: User story describing a requirement or goal.
title: "[STORY]: "
labels: ["story"]
body:
  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: e.g. STORY-001
    validations:
      required: true
  - type: input
    id: feature_link
    attributes:
      label: Feature Reference
      description: Link to parent feature
  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: As a <role> I want <goal> so that <benefit>
  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: List related tasks
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
  - type: textarea
    id: done
    attributes:
      label: Definition of Done
  - type: textarea
    id: notes
    attributes:
      label: Notes
