name: Verification
description: MVP or technical validation — automated or human verifier with clear instructions.
title: "[VERIFY]: "
labels: ["verification"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for validating that work meets MVP or technical quality standards.
        Verifications can be **automated** (scripts, CI), **human** (manual checks with instructions), or **both**.
  - type: input
    id: verification_id
    attributes:
      label: Verification ID
      description: e.g. VERIFY-001
    validations:
      required: true
  - type: dropdown
    id: verification_type
    attributes:
      label: Verification Type
      description: How will this verification be performed?
      options:
        - "Automated (script, CI job, pytest)"
        - "Human (manual steps with instructions)"
        - "Both (automated + human sign-off)"
    validations:
      required: true
  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What does this verification cover?
      options:
        - "Functionality (end-to-end behaviour, user flows)"
        - "Technical (architecture, ruff, pytest, type checking)"
        - "Both (full MVP validation)"
    validations:
      required: true
  - type: input
    id: related_issue
    attributes:
      label: Related Issue(s)
      description: Link to feature/story/task this verifies (e.g. #42, FEAT-001)
  - type: textarea
    id: instructions
    attributes:
      label: Verification Instructions
      description: Clear, step-by-step instructions for the verifier. For human verifications, be explicit so anyone can follow.
      placeholder: |
        **For automated:**
        - Command to run (e.g. `uv run pytest tests/test_foo.py`)
        - Expected outcome (e.g. all tests pass)
        
        **For human:**
        - Prerequisites (Docker up, .env configured)
        - Step 1: Do X, expect Y
        - Step 2: Do Z, expect W
        - Pass criteria: ...
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Checkboxes that define when verification passes
  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope
      description: What this verification does NOT cover (prevents scope creep)
  - type: textarea
    id: notes
    attributes:
      label: Notes
