"""Domain events for the Query Service bounded context.

Events are emitted at each stage of the RAG workflow:
1. QueryReceived — user question was received
2. ContextRetrieved — relevant document chunks were found
3. AnswerGenerated — LLM produced an answer
4. CitationIncluded — sources attached to the answer
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class DomainEvent:
    """Base class for all domain events.

    Attributes:
        event_id: Unique event identifier.
        timestamp: When the event occurred.
    """

    event_id: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class QueryReceived(DomainEvent):
    """Emitted when a user question is received by the system.

    Attributes:
        query_id: Unique identifier for the query.
        text: The question text (for audit logging).
        user_id: Optional user identifier.
        session_id: Optional session identifier.
    """

    query_id: str = ""
    text: str = ""
    user_id: str = ""
    session_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "event": "QueryReceived",
            "query_id": self.query_id,
            "text_snippet": self.text[:60] + "..." if len(self.text) > 60 else self.text,
            "user_id": self.user_id,
            "session_id": self.session_id,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class ContextRetrieved(DomainEvent):
    """Emitted when relevant document chunks have been retrieved.

    Attributes:
        query_id: The query that triggered the retrieval.
        chunk_count: Number of chunks retrieved.
        strategy: Retrieval strategy used (dense, sparse, hybrid).
    """

    query_id: str = ""
    chunk_count: int = 0
    strategy: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "event": "ContextRetrieved",
            "query_id": self.query_id,
            "chunk_count": self.chunk_count,
            "strategy": self.strategy,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class AnswerGenerated(DomainEvent):
    """Emitted when an answer has been generated by the LLM.

    Attributes:
        query_id: The query that triggered the generation.
        question: The original question text.
        answer: The generated answer text.
        confidence: Confidence level (high/medium/low).
        chunks_retrieved: Number of chunks used.
        average_similarity: Average similarity score.
        session_id: Optional session identifier.
    """

    query_id: str = ""
    question: str = ""
    answer: str = ""
    confidence: str = "low"
    chunks_retrieved: int = 0
    average_similarity: float = 0.0
    session_id: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "event": "AnswerGenerated",
            "query_id": self.query_id,
            "confidence": self.confidence,
            "chunks_retrieved": self.chunks_retrieved,
            "average_similarity": self.average_similarity,
            "session_id": self.session_id,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class CitationIncluded(DomainEvent):
    """Emitted when citations are attached to an answer.

    Attributes:
        query_id: The query identifier.
        citation_count: Number of citations included.
    """

    query_id: str = ""
    citation_count: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "event": "CitationIncluded",
            "query_id": self.query_id,
            "citation_count": self.citation_count,
            "timestamp": self.timestamp.isoformat(),
        }
